Add kanban-board
TonyDischein/TaskManager pull request #14
Opened 2022-09-30 12:24 UTC by TonyDischein

2022-09-30 12:38 UTC, TonyDischein commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import '@asseinfo/react-kanban/dist/styles.css';
Сразу хочу спросить тут вопрос.  Отрисовка компонента должна быть:
1) В контроллере как в примере?  (render(component: 'TaskBoard', props: {})) 
2) Или же достаточно в файле шаблона (как на данный момент)?

При реализации первого варианта возникает проблема с подключением модулей внутри компонент (2, 3 строки ).   <ExecJS::ProgramError: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.>" when prerendering TaskBoard with {}

Пока искал решение, нашёл в чате подключение стилей к доске, но намёка на то как это фиксить.

Так же на данный момент я не выполнял команду rails generate react:install так как вызов react_component в шаблоне работает и без этого.

2022-09-30 18:02 UTC, greybutton requested changes

2022-09-30 18:02 UTC, greybutton commented on app/views/web/boards/show.html.slim
> += react_component('TaskBoard')
почему это здесь? в задание же про контроллер написано

2022-09-30 18:02 UTC, greybutton commented on Gemfile
> +gem 'react-rails'
зачем этот гем?

2022-09-30 18:02 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import '@asseinfo/react-kanban/dist/styles.css';
первый вариант, возможно нужно поставить гем webpacker-react

2022-09-30 19:11 UTC, TonyDischein commented on Gemfile
> +gem 'react-rails'
Гуглёж 'react_component' первой ссылкой выдал мне первой ссылкой этот гем, поэтому я начал пытаться прикручивать его, и гуглить как отобразить компонент через контроллер. Думал что в задание может специально не было указано про установку этого гема.

2022-09-30 19:13 UTC, TonyDischein commented on app/views/web/boards/show.html.slim
> += react_component('TaskBoard')
С тем гемом что я начал использовать был гемор с вызовом внутри контроллера. Теперь исправил.

2022-09-30 19:14 UTC, TonyDischein commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import '@asseinfo/react-kanban/dist/styles.css';
Спасибо

2022-10-01 07:23 UTC, greybutton approved these changes

2022-10-01 09:32 UTC, merged