Implement functionality for working with tasks on kanban board
TonyDischein/TaskManager pull request #15
Opened 2022-10-02 14:20 UTC by TonyDischein

2022-10-02 15:39 UTC, TonyDischein commented on app/controllers/api/v1/tasks_controller.rb
> -    respond_with(task, serializer: TaskSerializer)
Вот здесь я хочу спросить немного помощи. Я понимаю что этот костыль убирает весь смысл  JsonResponder, но, я перечитал всё что нашёл по respond_with и так и не совсем понял почему здесь, если оставить respond_with, будет 406 ответ с неизвестным форматом, так как ответ придёт в виде текста.

Метод create при этом отрабатывает корректно, при том что и у create и у update одинаковые заголовки запроса в fetchHelper.  При дебаге обнаружил что в JsonResponder не попадаю, если у меня метод put. Сразу выходит Completed 406 Not Acceptable.

В общем вопрос в том в какую сторону копать. В сторону js или ruby

2022-10-02 16:02 UTC, greybutton requested changes

2022-10-02 16:02 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import ColumnHeader from '../ColumnHeader';
components/ColumnHeader 

для формы по аналогии

2022-10-02 16:02 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import KanbanBoard from '@lourenci/react-kanban';
вроде `@asseinfo/react-kanban` должен быть

2022-10-02 16:02 UTC, greybutton commented on package.json
> +    "humps": "^2.0.1",
не хватает qs

2022-10-02 16:02 UTC, greybutton commented on utils/fetchHelper.js
> +axios.defaults.headers.get['Accept'] = 'application/json';
уже есть Accept: '*/*',

2022-10-02 16:02 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> -    respond_with(task, serializer: TaskSerializer)
в руби, надо в routes.rb задать дефолтный формат для апи

2022-10-02 23:32 UTC, TonyDischein commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import ColumnHeader from '../ColumnHeader';
Исправил

2022-10-02 23:41 UTC, TonyDischein commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import KanbanBoard from '@lourenci/react-kanban';
Да, но тогда у меня в консоли отображается следующая ошибка Warning: Each child in a list should have a unique "key" prop  - https://github.com/asseinfo/react-kanban/issues/459 . На работоспособность текущего функционала это не влияет, но наличие самой ошибки не приятно. И так как её, как я понимаю, пока не исправили был выбор либо понижать react с 18, либо использовать старую версию канбан доски.

2022-10-02 23:42 UTC, TonyDischein commented on package.json
> +    "humps": "^2.0.1",
Добавил, хотя и не совсем понял от куда он был у меня до этого и почему его не было в package.json

2022-10-02 23:45 UTC, TonyDischein commented on utils/fetchHelper.js
> +axios.defaults.headers.get['Accept'] = 'application/json';
Исправил. Помог совет с добавлением формата в конфиг роутов. Без этого был 406 статус на get.

2022-10-02 23:47 UTC, TonyDischein commented on app/controllers/api/v1/tasks_controller.rb
> -    respond_with(task, serializer: TaskSerializer)
Спасибо, добавил, это помогло решить проблему с get запросами без явного указания Accept: json:application, однако,  метод put по прежнему мне шлёт 406 ответ, буду искать причину дальше.

2022-10-03 07:47 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> -    respond_with(task, serializer: TaskSerializer)
попробуй дефолт на неймспейс апи, а не отдельный ресурс. Все ресурсы будут жсон в апи неймспейсе

2022-10-03 07:49 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import KanbanBoard from '@lourenci/react-kanban';
хорошо, если что lourenci/react-kanban деприкейтед)

2022-10-03 11:15 UTC, TonyDischein commented on app/controllers/api/v1/tasks_controller.rb
> -    respond_with(task, serializer: TaskSerializer)
Добавил, и много ещё чего пытался делать, но пока всё там же. 
В независимости от того, что содержится в методе update, внутри метода respond_with происходит исключение по несоответствию типа запроса и ответа, хотя тип контента что у update что у put одинаковый.

Пробовал в axios заменить put на patch, но та же проблема.
Кажется как будто update не знает что ответить на json, хотя есть и respond_to :json в aplicationController default format в роутах.  Продолжу изучение, но уже начинает казаться что либо что то где закешировалось, либо какая то небольшая опечатка.

2022-10-03 16:18 UTC, greybutton requested changes

2022-10-03 16:18 UTC, greybutton commented on app/javascript/repositories/TasksRepository.js
> +  update(task = {}) {
здесь ид нужен

2022-10-03 16:18 UTC, greybutton commented on app/javascript/repositories/TasksRepository.js
> +    const path = routes.apiV1TaskPath(task);
здесь ид использовать

2022-10-03 16:18 UTC, greybutton commented on app/javascript/repositories/TasksRepository.js
> +    return FetchHelper.put(path, task);
здесь возможно надо передавать `{ task }` вместо `task`. в create может быть тоже

2022-10-03 16:23 UTC, TonyDischein commented on app/controllers/api/v1/tasks_controller.rb
> -    respond_with(task, serializer: TaskSerializer)
Пофиксил, не знаю правильно ли. 
Всё было на поверхности, а я не увидел. 
В общем, так как проходят тесты то с помощью debugger я посмотрел отличия в запросах, и увидел что мой запрос в браузере имеет следующий вид:
/api/v1/tasks/122.122
а запрос в тестах
/api/v1/tasks/122

Как итог я пользовался не правильно методом apiV1TaskPath, так как, вторым параметром туда надо передавать не id, а формат. Сейчас я передаю без формата, и всё работает, но если нужно, то могу переделать так apiV1TaskPath(task, 'json')
/api/v1/tasks/122.json
такой вариант тоже отработает.

2022-10-03 16:27 UTC, TonyDischein commented on app/javascript/repositories/TasksRepository.js
> +  update(task = {}) {
Вот тут https://github.com/TonyDischein/TaskManager/pull/15#discussion_r985992394 описал причину удаление. Так как если есть id task, то он дважды клеит через точку id. Без явного параметра id, я так понимаю он забирает его из task

2022-10-03 16:31 UTC, TonyDischein commented on app/javascript/repositories/TasksRepository.js
> +    return FetchHelper.put(path, task);
Удалил обёртку так как проверил работу в обоих вариантах и она одинаковая. Отличается "RAW_POST_DATA"
без {} - "{\"id\":122,\"name\":\"111\",\"description\":\"111\",\"assignee_id\":null,\"author_id\":4}"
c {} - "{\"task\":{\"id\":122,\"name\":\"111\",\"description\":\"111\",\"assignee_id\":null,\"author_id\":4}}"}

Но на текущий функционал, вроде, это не влияет

2022-10-03 16:51 UTC, greybutton commented on app/javascript/repositories/TasksRepository.js
> +    return FetchHelper.put(path, task);
как проверял? в обоих случаях создалась таска?

2022-10-03 16:53 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> -    respond_with(task, serializer: TaskSerializer)
если ид передаешь в apiV1TaskPath, то второй параметр не надо передавать

2022-10-03 16:54 UTC, TonyDischein commented on app/javascript/repositories/TasksRepository.js
> +    return FetchHelper.put(path, task);
Да, в обоих случаях создалась и без ошибок в консоли
А отличия в RAW_POST_DATA я проверял только на update, но сейчас ещё и на create проверю.

2022-10-03 16:55 UTC, greybutton commented on app/javascript/repositories/TasksRepository.js
> +    const path = routes.apiV1TasksPath(task);
здесь task не надо передавать

2022-10-03 17:07 UTC, TonyDischein commented on app/controllers/api/v1/tasks_controller.rb
> -    respond_with(task, serializer: TaskSerializer)
Исправил, ступил. Так то да, этот же метод только путь возвращает, ему не нужны подробности о сущности

2022-10-03 17:24 UTC, TonyDischein commented on app/javascript/repositories/TasksRepository.js
> +    const path = routes.apiV1TasksPath(task);
Исправил

2022-10-03 17:25 UTC, TonyDischein commented on app/javascript/repositories/TasksRepository.js
> +    return FetchHelper.put(path, task);
Вернул обёртку обратно. Хоть работает и одинаково, но отслеживать запросы с ней в браузере удобнее и выглядят они так более целостно

2022-10-03 17:26 UTC, TonyDischein commented on app/javascript/repositories/TasksRepository.js
> +  update(task = {}) {
Исправил

2022-10-03 17:27 UTC, TonyDischein commented on app/javascript/repositories/TasksRepository.js
> +    const path = routes.apiV1TaskPath(task);
Заменил task на id

2022-10-04 06:19 UTC, greybutton approved these changes

2022-10-04 07:42 UTC, merged