Add assignee selection for tasks, user and task presenters
TonyDischein/TaskManager pull request #16
Opened 2022-10-04 12:14 UTC by TonyDischein

2022-10-04 13:49 UTC, TonyDischein commented on utils/PropTypesPresenter.js
> +}
Вопрос ещё появился, пока делал это задание. Эта директория (utils), добавляется в блоке - TaskManager. Задачи. И там вроде как не было сказано куда её добавлять, там было так 'Cоздадим в utils/keysConverter.js'. Так вот я и поместил её в корень рельсов, но теперь, мне кажется, что там в задание был указан относительный путь от app/javascript.

Вопрос как быть, оставить ли тут, или перенести в app/javascript/utils? Или перенести в следующем задании

2022-10-04 18:03 UTC, greybutton requested changes

2022-10-04 18:03 UTC, greybutton commented on app/javascript/repositories/UsersRepository.js
> +export default {
show забыл

2022-10-04 18:03 UTC, greybutton commented on app/javascript/presenters/TaskPresenter.js
> +  author: PropTypes.object,
transitions тоже можно добавить

2022-10-04 18:03 UTC, greybutton commented on utils/PropTypesPresenter.js
> +}
переноси, файлы жс все будут в app/javascript

2022-10-04 19:01 UTC, TonyDischein commented on utils/PropTypesPresenter.js
> +}
Ок, перенёс

2022-10-04 19:03 UTC, TonyDischein commented on app/javascript/repositories/UsersRepository.js
> +export default {
Ну не то что бы забыл, он просто не используется, поэтому я не стал его описывать. Но хотя да, так как он есть и в контроллере и в js-routes то логичнее было добавить.
Добавил

2022-10-04 19:03 UTC, TonyDischein commented on app/javascript/presenters/TaskPresenter.js
> +  author: PropTypes.object,
Сделано

2022-10-05 07:03 UTC, greybutton approved these changes

2022-10-05 08:26 UTC, merged