Add Coveralls
TonyDischein/TaskManager pull request #19
Opened 2022-10-09 20:18 UTC by TonyDischein

2022-10-09 21:13 UTC, TonyDischein commented on test/test_helper.rb
> +    c.single_report_path = 'coverage/lcov.info'
Можно, пожалуйста, подскзаку по тому куда тут копать?

На данный момент covarage/ добавлен в .gitignore и файл coverage/lcov.info должен генерироваться на github actions в контейнере после запуска тестов. Однако это не происходит и возникает ошибка Error: Lcov file not found. При этом, когда я проверяю локально, то файл создаётся. Пробовал уже разные комбинации, но ничего не помогает, только если исключать директорию из .gitignore и запускать тесты локально и пушить результаты тестов в репозиторий, тогда данные отправляются в Coveralls

2022-10-11 18:17 UTC, greybutton commented on test/test_helper.rb
> +    c.single_report_path = 'coverage/lcov.info'
пробовал не задавать single_report_path?

2022-10-11 18:17 UTC, greybutton commented on test/test_helper.rb
> +    c.single_report_path = 'coverage/lcov.info'
можем быть такой путь сработает `'./coverage/lcov.info'`

2022-10-11 18:19 UTC, greybutton requested changes

2022-10-11 18:19 UTC, greybutton commented on test/test_helper.rb
> +SimpleCov.start('rails') do
покрытие лучше генерировать только если тесты через CI запущены, иначе всегда будут генерироваться на запуск тестов, а всегда не нужно

2022-10-11 18:19 UTC, greybutton commented on .github/workflows/main.yml
> +          github-token: ${{ secrets.GITHUB_TOKEN }}
может быть здесь какой параметр есть указать путь до покрытия

2022-10-11 23:05 UTC, TonyDischein commented on test/test_helper.rb
> +    c.single_report_path = 'coverage/lcov.info'
Пробовал не задавать single_report_path, тогда путь имеет вид /task_manager/coverage/lcov/task_manager.lcov, однако даже его явное указание параметром  path-to-lcov не помогает. Пробовал с путём './coverage/lcov.info', файл так же не находится
![image](https://user-images.githubusercontent.com/41506918/195214176-35311f7c-b27b-4b7f-be5d-4b2ef1c61afb.png)

2022-10-11 23:06 UTC, TonyDischein commented on test/test_helper.rb
> +SimpleCov.start('rails') do
Исправил, через добавлению переменной CI в docker-compose.ci.yml.

2022-10-11 23:11 UTC, TonyDischein commented on .github/workflows/main.yml
> +          github-token: ${{ secrets.GITHUB_TOKEN }}
Пробовал path-to-lcov, который указан в доках, всё так же. Хотя там и указано что по дефолту путь './coverage/lcov.info'.

В общем продолжу копать. Ещё что не понятно, что если выводить список файлов и директорий корневого каталога в коде в конце файла test_helper, то на момент вывода списка, файлов там действительно нет. Хотя они и появляются в конце выполнения скрипта в директории

2022-10-12 19:51 UTC, greybutton commented on test/test_helper.rb
> +SimpleCov.start('rails') do
SimpleCov.start('rails') внутри ифа можно сделать

2022-10-12 19:52 UTC, greybutton commented on test/test_helper.rb
> +      c.single_report_path = '/home/runner/work/TaskManager/TaskManager/coverage/lcov.info'
ну уверен что так должно быть, может './coverage/lcov.info' вместе с path-to-lcov: ${{ github.workspace }}/coverage/lcov.info

2022-10-12 20:02 UTC, TonyDischein commented on test/test_helper.rb
> +      c.single_report_path = '/home/runner/work/TaskManager/TaskManager/coverage/lcov.info'
Попробую, спасибо, вроде я так уже делал. Текущий конфиг выдаёт то что, на скрине, и по сути то пути где искать и путь куда создавать сходятся, но чего то не хватает
![image](https://user-images.githubusercontent.com/41506918/195436783-f7d8767f-bf9f-44d3-8ae9-5bed5bda8017.png)

2022-10-16 22:05 UTC, TonyDischein commented on docker-compose.ci.yml
> +      - ./coverage:/task_manager/coverage
Дело было в этой строке. Файлы появлялись, но не пробрасывались в контейнер выше

2022-10-16 22:09 UTC, TonyDischein commented on docker-compose.ci.yml
> +      - ./coverage:/task_manager/coverage
Сейчас данные отправляются
![image](https://user-images.githubusercontent.com/41506918/196060665-e2d53c1e-2f72-4ce8-8610-599aa4661a0c.png)

2022-10-16 22:11 UTC, TonyDischein commented on README.md
> +[![Coverage Status](https://coveralls.io/repos/github/TonyDischein/TaskManager/badge.svg?branch=develop)](https://coveralls.io/github/TonyDischein/TaskManager?branch=develop)
На данный момент бэйдж отображается как unknown, но это, как я понимаю, исправиться если изменения из этой ветки попадут в деволоп, и в coveralls  я рефрешну badge

2022-10-16 22:56 UTC, TonyDischein commented on .github/workflows/main.yml
> +    environment: development
Я правильно понял, что нужно было создавать токен через environment, а не просто secrets?
![image](https://user-images.githubusercontent.com/41506918/196061164-2797ccaf-b74d-4a57-8564-c3df2c0f62e6.png)

И ещё несколько вопросов:
1) В данном случае, при выполнении из github action, токе не используется, нужно ли тогда добавлять 14 строку.
2) Вопрос касается следующих задач (Rollbar и newelic) и в целом про понимание ключей. Я правильно понимаю что при локальной разработке используются токены в коде, но при публикации на github, они заменяются на переменные окружения из github/workflows? Которые ссылаются на секретные ключи в настройках репозитория. Я к тому, что нет же возможности пробрасывать ключе через docker-compose внутри репозитория. 

Я к тому что на для newrelic используется токен в коде, но на рендер проект собирается без githb actions, а ключи прописываются в в фалах  githb actions, это как то контрится? Просто я совсем поплыл с этими токенами
, хотя бы небольшую подсказку, а то в доках всё упирается в .github/workflow, но опять же, получается есть возможность к нему обращаться и из локального репозитория?

2022-10-17 06:58 UTC, greybutton commented on .github/workflows/main.yml
> +    environment: development
0 да, в environment variables добавлять
1 думаю нет, покрытие не зависит от environment
2 в коде могут подставлять фейковые строчки под переменные среды через докер-композе.ямл например. При разработке роллбар и ньюрелик не нужны. Это инструменты для прода, локально и так можно увидеть ошибки, а статистику локальную нет особо смысла собирать

Насчет рендера и переменных среды пока не знаю, возможно в самом рендере надо тоже добавлять переменные среды для роллбара и ньюрелика. А делаем через githb actions чтобы у вас код мог работать с переменными среды, тогда код приложения сможет работать и с githb actions и с рендером

2022-10-17 06:58 UTC, greybutton approved these changes

2022-10-17 20:43 UTC, TonyDischein commented on .github/workflows/main.yml
> +    environment: development
Спасибо

2022-10-17 20:44 UTC, TonyDischein commented on test/test_helper.rb
> +SimpleCov.start('rails') do
Сделал

2022-10-17 20:44 UTC, merged