Add new relic
TonyDischein/TaskManager pull request #22
Opened 2022-10-13 13:39 UTC by TonyDischein

2022-10-13 14:30 UTC, TonyDischein commented on newrelic.yml:Zone.Identifier
> +HostUrl=https://one.eu.newrelic.com/
После добавления этих файлов, отчёты стали поступать, ниже будет скрин. Однако в документации на 5 шаге необходимо сделать следующее:
![image](https://user-images.githubusercontent.com/41506918/195621928-c5c6620f-1ff0-4fe3-8d3c-537f267f28dc.png)

данный шаг я пропустил, однако отчёты всё равно отправляются, нормально ли это? 

И если этот шаг обязателен то есть проблемы с деплоем, так как не возможности запустить команду.

![image](https://user-images.githubusercontent.com/41506918/195619595-62c40259-354c-434d-90fd-965dcfc3b050.png)

2022-10-13 15:48 UTC, greybutton requested changes

2022-10-13 15:48 UTC, greybutton commented on newrelic.yml
> +  license_key: eu01xxe4da45eb79f243d9037ba6f91577afNRAL
токены не хранят в коде. сгенерируй новый токен и добавь его через переменные окружения (environment variables)

2022-10-13 15:48 UTC, greybutton commented on newrelic.yml:Zone.Identifier
> +HostUrl=https://one.eu.newrelic.com/
где нашел, что надо newrelic.yml:Zone.Identifier добавить?

2022-10-13 16:05 UTC, TonyDischein commented on newrelic.yml:Zone.Identifier
> +HostUrl=https://one.eu.newrelic.com/
Ну я всё делал по этой инструкции что на скрине. Сам инструкция на сайте https://one.eu.newrelic.com/ (она там через всплывающее окно). На 4 шаге, после выполнения rails restart, этот файл появляется сам. Я не предал этому значения, думал что так и должно быть.
![image](https://user-images.githubusercontent.com/41506918/195647720-34edbb20-5e56-42c2-8bd5-f6721b264f67.png)

2022-10-13 19:47 UTC, greybutton commented on newrelic.yml:Zone.Identifier
> +HostUrl=https://one.eu.newrelic.com/
ну ладно, раньше прост ни у кого не было такого файла)

2022-10-18 09:43 UTC, TonyDischein commented on newrelic.yml:Zone.Identifier
> +HostUrl=https://one.eu.newrelic.com/
Сделал

2022-10-18 09:43 UTC, TonyDischein commented on newrelic.yml
> +  license_key: eu01xxe4da45eb79f243d9037ba6f91577afNRAL
Добавил

2022-10-18 14:56 UTC, TonyDischein commented on newrelic.yml
> +  license_key: { { NEWRELIC_LICENSE_KEY } }
Вынес в переменную окружения, отчёты приходят:
![image](https://user-images.githubusercontent.com/41506918/196466029-e871348f-d01d-4f49-adee-b5c5a4ab6446.png)

![image](https://user-images.githubusercontent.com/41506918/196466271-9c73a161-0d81-47ed-9b3b-95aa4fc02b80.png)

2022-10-18 17:10 UTC, greybutton approved these changes

2022-10-21 17:31 UTC, merged