Add rollbar
TonyDischein/TaskManager pull request #23
Opened 2022-10-13 15:15 UTC by TonyDischein

2022-10-13 15:51 UTC, TonyDischein commented on config/rollbar.rb
> +  config.access_token = 'cd6eb304ed624be2a5551fd62dabd4a5'
Прикрутил, правда опять есть вопросы. В общем, то что отчёты приходят будем ниже скрин с исключением деления на 0 (добавил в метод на показ задач, а потом удалил).
![image](https://user-images.githubusercontent.com/41506918/195644582-6172bb9e-cb3c-4501-8dde-b85d939b529f.png)

А вопросы про то что:
1) Нормально ли что токен лежит в коде в публичном доступе
2) Нужно ли rollbar связывать с render?

2022-10-13 18:06 UTC, greybutton requested changes

2022-10-13 18:06 UTC, greybutton commented on config/rollbar.rb
> +  config.access_token = 'cd6eb304ed624be2a5551fd62dabd4a5'
1 не нормально. токены не хранят в коде. сгенерируй новый токен и добавь его через переменные окружения (environment variables)
2 нет, роллбар сам по себе по идее должен работать. не важно рендер, хероку или еще что то

2022-10-13 18:06 UTC, greybutton commented on config/environment.rb
> +end
это зачем?

2022-10-13 18:53 UTC, TonyDischein commented on config/environment.rb
> +end
Это я взял из этого пункта документации (прикреплён скрином). Насколько я понял, это позволяет отправлять исключения возникшее на этапе инициализации, а не на этапе бизнес логики. Хотя на данный момент я не совсем понимаю как можно даже такую ситуацию с эмитировать.

![image](https://user-images.githubusercontent.com/41506918/195682077-cac6de8d-d021-4e67-95c5-5a7156ae6e20.png)


В общем это убрать?

2022-10-13 19:45 UTC, greybutton commented on config/environment.rb
> +end
да, можно убрать

2022-10-18 09:44 UTC, TonyDischein commented on config/environment.rb
> +end
Убрал

2022-10-18 09:44 UTC, TonyDischein commented on config/rollbar.rb
> +  config.access_token = 'cd6eb304ed624be2a5551fd62dabd4a5'
Добавил токен

2022-10-18 14:52 UTC, TonyDischein commented on config/initializers/rollbar.rb
> +  config.access_token = ENV['ROLLBAR_TOKEN']
Добавил через переменную окружения. В render их проставил в интерфейсе:
![image](https://user-images.githubusercontent.com/41506918/196463040-fd04f4e3-9848-4884-93c5-74a252049b99.png)

Добавил строку с пробросом исключения, отчёты стали приходить:
![image](https://user-images.githubusercontent.com/41506918/196463431-4943623f-8d5e-4198-a8d2-29d8a6009829.png)

Только сейчас у меня деплой приложения сменил адрес, так как после некоторых попыток старая сборка перестала собираться... Ну и там ещё проблемы что по бесплатной подписке можно только одну базу создавать.

Вот тут сейчас актуальный деплой, собирается с ветки на которой уже есть и new relic и rollbar, и пробрасывается исключение если заходить в задачи, имя которых = test
https://task-manager-fwtb.onrender.com/

После мержа верну нормальную ветку в render и обновлю ссылку в readme, только есть вопрос:
1) Нужно ли будет обновить ссылку на дерлой в личном кабинете в разделе деплоя?

2022-10-18 17:10 UTC, greybutton commented on config/initializers/rollbar.rb
> +  config.access_token = ENV['ROLLBAR_TOKEN']
можно обновить ссылку

2022-10-18 17:10 UTC, greybutton approved these changes

2022-10-21 17:15 UTC, merged