Add email notifications when working with tasks and reset password by email
TonyDischein/TaskManager pull request #25
Opened 2022-10-21 21:57 UTC by TonyDischein

2022-10-31 06:05 UTC, greybutton requested changes

2022-10-31 06:05 UTC, greybutton commented on app/mailers/user_mailer.rb
> +  def get_recipients_list(user)
почему юзер передается как параметр, а таска нет?

2022-10-31 06:05 UTC, greybutton commented on app/mailers/user_mailer.rb
> +    user, @task = get_message_data
1 `@task` отдает неявным программированием, любая функция может объявить переменную для класса. Через @ обычно в сетапе или инициализаторе объявляют, в общем в одном месте где то обычно такое объявление
2 get_message_data немного странно засовывать все в массив, сомнительная экономия строчек кода)

2022-10-31 06:05 UTC, greybutton commented on test/controllers/web/password_resets_controller_test.rb
> +  end
не понял тест и в тесте контроллеров должен быть один запрос на бэк

2022-10-31 06:05 UTC, greybutton commented on test/controllers/web/password_resets_controller_test.rb
> +    user.reload
вместо запроса нужно подготовку данных в тесте сделать

2022-10-31 06:05 UTC, greybutton commented on app/controllers/concerns/recoverable.rb
> +    before_update :clear_reset_password_token, if: :password_digest_changed?
а где функция password_digest_changed?

2022-11-03 14:54 UTC, TonyDischein commented on app/mailers/user_mailer.rb
> +  def get_recipients_list(user)
Потому что, как я понял, я криво описал этот метод, да и весь класс. И юзер у меня был переменной локальной, а таска переменной экземпляра, из за чего мне не требовалось её передавать. Исправил реализацию.

А вообще я не совсем уверен в том, нужно ли это тут. Смысл этого метода в том что бы сообщение приходило не только создателю и исполнителю задачи, а ещё и текущему юзеру, который внёс эту задачу изменение.  В общем в методе по удалению сообщение приходит только тому пользователю, который удалил, но если надо могу добавить и этот метод, что бы приходило сообщение ещё и создателю и исполнителю.

2022-11-03 14:55 UTC, TonyDischein commented on app/mailers/user_mailer.rb
> +    user, @task = get_message_data
Понял, вроде, исправил

2022-11-03 14:57 UTC, TonyDischein commented on test/controllers/web/password_resets_controller_test.rb
> +  end
Запрос оставил один, А смысл теста в том, что с токеном получается зайти на страницу сброса пароля. Так как если в url вбить не корректный токен то произойдёт редирект на страницу входа с сообщением что токен истёк.

2022-11-03 14:57 UTC, TonyDischein commented on test/controllers/web/password_resets_controller_test.rb
> +    user.reload
Исправил

2022-11-03 15:00 UTC, TonyDischein commented on app/controllers/concerns/recoverable.rb
> +    before_update :clear_reset_password_token, if: :password_digest_changed?
Тут я опять тупанул и закинул этот файл не в тот concernes. логичнее его нахождение в директории с моделями. Сейчас перенёс. Ну и я так понимаю что это магия рельсов, если в модели дописываем к названию столбца _changed? то можно понять был ли изменён этот атрибут.

2022-11-06 19:03 UTC, greybutton approved these changes

2022-11-06 19:03 UTC, greybutton commented on app/controllers/web/password_resets_controller.rb
> +    params.require(:password_reset_new_form).permit(:email)
в целом можно было оставить params.require(:password_reset), а пермиты разные в самих формах сделать

2022-11-06 19:03 UTC, greybutton commented on app/controllers/web/password_resets_controller.rb
> +    if @password_reset_edit.update
на будущее, обычно не переопределяют метод модели и по другому делают чтобы ошибки валидации вернуть, но сейчас ладно, пойдет и так)

2022-11-07 22:46 UTC, TonyDischein commented on app/controllers/web/password_resets_controller.rb
> +    params.require(:password_reset_new_form).permit(:email)
Попытался это сделать, но словил пару ошибок, на этапе передачи данных в форму. Я правильно понял, нужно прям в форме это реализовывать, а не вот так?:

create
@password_reset = PasswordResetNewForm.new(password_reset).permit(:email)

update
@password_reset = PasswordResetUpdateForm.new(password_reset).permit(:password, :password_confirmation, :password_reset_token)

def password_reset
    params.require(:password_reset_form)

2022-11-07 22:51 UTC, TonyDischein commented on app/controllers/web/password_resets_controller.rb
> +    if @password_reset_edit.update
Ок, спасибо. Я видел в статьях по этому патерну как что то подобное делали методом submit, но вот его реализации сильно отличались в разных статьях

2022-11-09 10:49 UTC, greybutton commented on app/controllers/web/password_resets_controller.rb
> +    params.require(:password_reset_new_form).permit(:email)
можешь оставить как есть, я заапрувил

2022-11-10 17:21 UTC, TonyDischein commented on app/controllers/web/password_resets_controller.rb
> +    params.require(:password_reset_new_form).permit(:email)
Ок

2022-11-10 17:22 UTC, merged