Add state machine for task status
TonyDischein/TaskManager pull request #6
Opened 2022-09-22 09:44 UTC by TonyDischein

2022-09-22 09:52 UTC, TonyDischein commented on test/factories/sequence.rb
> +  sequence(:state) { 'new_task' }
Понимаю что нужно придерживаться одного стиля при передаче блоков, но понял что ранее немного тупил и тут было бы лучше, наверное, использовать такую передачу, чем через do.  При этом не стал исправлять ранние вызовы, что бы не загрязнять пр лишней логикой. 
В общем , оставить ли так или переписать через do end?

2022-09-22 10:28 UTC, YJorge commented on app/models/task.rb
> +    event :archived do
название не описывает действие. Нужно использовать глагол

2022-09-22 10:30 UTC, YJorge commented on app/models/task.rb
> +      transition new_task: :in_development, in_qa: :in_development, in_code_review: :in_development
сложный синтаксис, пока поймешь что и куда переводится 5 лет пройдет. Нужно упростить

2022-09-27 07:52 UTC, greybutton requested changes

2022-09-27 07:52 UTC, greybutton commented on app/models/task.rb
> +      transition new_task: :archived
почему в одну строку не сделать?

2022-09-27 07:52 UTC, greybutton commented on app/models/task.rb
> +      transition Task.predevelop_states => :in_development
1 необязательно выносить массив в функцию 
2 именование не совсем подходящее, стейты :in_qa, :in_code_review это не пред разработка

2022-09-27 07:52 UTC, greybutton commented on test/factories/sequence.rb
> +  sequence(:state) { 'new_task' }
для стейта sequence можно убрать

2022-09-27 10:13 UTC, greybutton approved these changes

2022-09-27 11:32 UTC, merged